<a href="https://colab.research.google.com/github/rafaellopezgarcia/colab_notebooks/blob/main/numpy_pytorch_differences_and_similarities.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy and PyTorch. Differences and similarities.

## Reverse torch and numpy


- `[::-1]` reversed Python lists and NumPy arrays
- `[::-1]` does not work with PyTorch

- `reverse` returns an iterator object for Python lists and NumPy arrays
- `reverse` returns the inverted one-dimensional tensor for PyTorch tensors

- `np.flip` and `torch.flip` are able to reverse a one-dimensional tensor as well
- `torch.flip` requires to specify the `dims` parameter

In [ ]:
numbers = [1, 2 , 3, 4, 5]
np_numbers = np.array(numbers)
torch_numbers = torch.tensor(numbers)

print(numbers)
print(np_numbers)
print(torch_numbers)

print("Reverse with slicing")
print(numbers[::-1])
print(np_numbers[::-1])
#print(torch_numbers[::-1]) Does not work

print("Reverse with reversed")
print(list(reversed(numbers)))
print(list(reversed(np_numbers)))
print(reversed(torch_numbers))

print("Reverse with flip")
print(np.flip(np_numbers))
print(torch.flip(torch_numbers, dims=[0]))



#print(torch_numbers[::-1]) Does not work

[1, 2, 3, 4, 5]
[1 2 3 4 5]
tensor([1, 2, 3, 4, 5])
Reverse with slicing
[5, 4, 3, 2, 1]
[5 4 3 2 1]
Reverse with reversed
[5, 4, 3, 2, 1]
[5, 4, 3, 2, 1]
tensor([5, 4, 3, 2, 1])
Reverse with flip
[5 4 3 2 1]
tensor([5, 4, 3, 2, 1])


## Creating one-dimensional array/tensor from 1 to n

In [ ]:
numbers = list(range(0, 6))
np_numbers = np.arange(0, 6)
torch_numbers = torch.arange(0, 6)

print(numbers)
print(np_numbers)
print(torch_numbers)


[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]
tensor([0, 1, 2, 3, 4, 5])


## Cumulative sum

- `np.cumsum` and `torch.cumsum` compute the cumulative sum
- `torch.cumsum` requires to specify the dimension over which the cumulative sum is computed

In [ ]:


np_numbers_cumsum = np.cumsum(np_numbers)
torch_numbers_cumsum = torch.cumsum(torch_numbers, dim=0)

print("Cumulative sum")
print(np_numbers_cumsum)
print(torch_numbers_cumsum)



[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]
tensor([0, 1, 2, 3, 4, 5])
Cumulative sum
[ 0  1  3  6 10 15]
tensor([ 0,  1,  3,  6, 10, 15])


## Random

- `np.random.seed` to manually specify a random seed in NumPy
- `torch.manual_seed` to manually specify a random seed in PyTorch

- `np.random.randn` to create random numbers with NumPy
- `torch.randn` to create random numbers with PyTorch

- `np.random.randint` to create random integers with NumPy
- `torch.randint` to create random integers with PyTorch

In [ ]:
torch.manual_seed(1336)
np.random.seed(1336)

np_random_numbers = np.random.randn(10)
torch_random_numbers = torch.randn(10)

print(np_random_numbers)
print(torch_random_numbers)

np_random_integers = np.random.randint(0, 10, [10])
torch_random_integers = torch.randint(0, 10, (10,))

print(np_random_integers)
print(torch_random_integers)

[ 1.04847236  0.99436432 -0.11980863  2.24886822 -0.01000265  1.64555138
 -2.13381788  0.65259954  1.27896194  1.13448778]
tensor([-0.8234,  0.8039,  1.6267,  0.9930, -0.1023,  0.7109,  0.0594, -1.4874,
        -0.9464,  1.6533])
[8 9 2 3 3 6 1 8 6 3]
tensor([5, 3, 2, 4, 0, 2, 3, 3, 2, 0])
